#!/bin/bash
set -euo pipefail


##
wget -nc ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_29_sqlite.tar.gz
wget -nc ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/chembl_29.fa.gz

##
if [[ ! -d "chembl_29_sqlite" ]]; then
  tar -zxvf chembl_29_sqlite.tar.gz
fi

##
if [[ ! -d "tables" ]]; then
  mkdir -p tables
    for table in ACTIVITIES ASSAYS COMPONENT_CLASS COMPOUND_STRUCTURES PROTEIN_FAMILY_CLASSIFICATION TARGET_COMPONENTS TARGET_DICTIONARY; do
  # for table in ACTION_TYPE ACTIVITIES ACTIVITY_PROPERTIES ACTIVITY_SMID ACTIVITY_STDS_LOOKUP ACTIVITY_SUPP ACTIVITY_SUPP_MAP ASSAY_CLASS_MAP ASSAY_CLASSIFICATION ASSAY_PARAMETERS ASSAY_TYPE ASSAYS ATC_CLASSIFICATION BINDING_SITES BIO_COMPONENT_SEQUENCES BIOASSAY_ONTOLOGY BIOTHERAPEUTIC_COMPONENTS BIOTHERAPEUTICS CELL_DICTIONARY CHEMBL_ID_LOOKUP COMPONENT_CLASS COMPONENT_DOMAINS COMPONENT_GO COMPONENT_SEQUENCES COMPONENT_SYNONYMS COMPOUND_PROPERTIES COMPOUND_RECORDS COMPOUND_STRUCTURAL_ALERTS COMPOUND_STRUCTURES CONFIDENCE_SCORE_LOOKUP CURATION_LOOKUP DATA_VALIDITY_LOOKUP DEFINED_DAILY_DOSE DOCS DOMAINS DRUG_INDICATION DRUG_MECHANISM FORMULATIONS FRAC_CLASSIFICATION GO_CLASSIFICATION HRAC_CLASSIFICATION INDICATION_REFS IRAC_CLASSIFICATION LIGAND_EFF MECHANISM_REFS METABOLISM METABOLISM_REFS MOLECULE_ATC_CLASSIFICATION MOLECULE_DICTIONARY MOLECULE_FRAC_CLASSIFICATION MOLECULE_HIERARCHY MOLECULE_HRAC_CLASSIFICATION MOLECULE_IRAC_CLASSIFICATION MOLECULE_SYNONYMS ORGANISM_CLASS PATENT_USE_CODES PREDICTED_BINDING_DOMAINS PRODUCT_PATENTS PRODUCTS PROTEIN_CLASS_SYNONYMS PROTEIN_CLASSIFICATION PROTEIN_FAMILY_CLASSIFICATION RELATIONSHIP_TYPE RESEARCH_COMPANIES RESEARCH_STEM SITE_COMPONENTS SOURCE STRUCTURAL_ALERT_SETS STRUCTURAL_ALERTS TARGET_COMPONENTS TARGET_DICTIONARY TARGET_RELATIONS TARGET_TYPE TISSUE_DICTIONARY USAN_STEMS VARIANT_SEQUENCES; do
    sqlite3 -header -csv chembl_29_sqlite/chembl_29.db "SELECT * from ${table};" \
      > tables/${table}.csv
  done
fi

##
if [[ ! -f "chembl_29_fa.tsv" ]]; then
  seqkit fx2tab chembl_29.fa.gz > chembl_29_fa.tsv
fi

##
mkdir -p data
